adminapp/urls.py
from django.urls import path

from adminapp.views import users, categories, products
from controllers import ListViews, CreateViews, UpdateViews, DeleteViews, \
    DetailViews

app_name = 'adminapp'

urlpatterns = [
    # users

    # FBV
    # path('users/index/', users.index, name='users'),
    # path('users/index/<int:page>', users.index, name='users_page'),
    # path('users/create/', users.create, name='user_create'),
    # path('users/read/<int:pk>', users.read, name='user_read'),
    # path('users/update/<int:id>', users.update, name='user_update'),
    # path('users/delete/<int:pk>/', users.delete, name='user_delete'),

    # CBV
    path('users/index/', ListViews.UserListView.as_view(), name='users'),
    path('users/index/<int:page>/', ListViews.UserListView.as_view(),
         name='users_page'),
    path('users/create/', CreateViews.UserCreateView.as_view(),
         name='user_create'),
    path('users/read/<int:pk>/', DetailViews.UserDetailView.as_view(),
         name='user_read'),
    path('users/update/<int:pk>/', UpdateViews.UserUpdateView.as_view(),
         name='user_update'),
    path('users/delete/<int:pk>/', DeleteViews.UserDeleteView.as_view(),
         name='user_delete'),

    # categories

    # FBV
    # path('categories/index/', categories.index, name='categories'),
    # path('categories/create/', categories.create, name='category_create'),
    # path('categories/read/<int:pk>/', categories.read, name='category_read'),
    # path('categories/update/<int:pk>/', categories.update,
    #      name='category_update'),
    # path('categories/delete/<int:pk>/', categories.delete,
    #      name='category_delete'),

    # CBV
    path('categories/index/', ListViews.CategoryListView.as_view(),
         name='categories'),
    path('categories/index/<int:page>/', ListViews.CategoryListView.as_view(),
         name='categories_page'),
    path('categories/create/', CreateViews.CategoryCreateView.as_view(),
         name='category_create'),
    path('categories/read/<int:pk>/', DetailViews.CategoryDetailView.as_view(),
         name='category_read'),
    path('categories/update/<int:pk>/',
         UpdateViews.CategoryUpdateView.as_view(),
         name='category_update'),
    path('categories/delete/<int:pk>/',
         DeleteViews.CategoryDeleteView.as_view(),
         name='category_delete'),

    # products

    # FBV
    # path('products/list/<int:pk>/', products.list_by_category,
    #      name='products'),
    # path('products/list/<int:pk>/<int:page>/', products.list_by_category,
    #      name='products_page'),
    # path('products/create/<int:pk>/', products.create, name='product_create'),
    # path('products/read/<int:pk>/', products.read, name='product_read'),
    # path('products/update/<int:pk>/', products.update, name='product_update'),
    # path('products/delete/<int:pk>/', products.delete, name='product_delete'),

    # CBV
    path('products/list/<int:pk>/', ListViews.ProductListView.as_view(),
         name='products'),
    path('products/list/<int:pk>/<int:page>/',
         ListViews.ProductListView.as_view(),
         name='products_page'),
    path('products/create/<int:pk>/', CreateViews.ProductCreateView.as_view(),
         name='product_create'),
    path('products/read/<int:pk>/', DetailViews.ProductDetailView.as_view(),
         name='product_read'),
    path('products/update/<int:pk>/', UpdateViews.ProductUpdateView.as_view(),
         name='product_update'),
    path('products/delete/<int:pk>/', DeleteViews.ProductDeleteView.as_view(),
         name='product_delete'),

    # orders
    path('order/restore/<int:pk>/', UpdateViews.OrderItemsUpdate.as_view(),
         name='order_restore'),
    path('orders/list/', ListViews.OrderList.as_view(),
         name='orders'),
    path('orders/list/<int:page>/', ListViews.OrderList.as_view(),
         name='orders_page'),

]

authapp/urls.py
from django.urls import path

import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    path('', controller.redirect_to_login, name='index'),
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),
    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/',
         controller.verify, name='verify'),
]

geekmarket/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
import mainapp.views as controller

urlpatterns = [
    path('contacts/', controller.contacts, name='contacts'),

    path('products/', include('mainapp.catalog_urls', namespace='catalog')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='home')),

    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

adminapp/models/categories.py
from mainapp.models import Category
from django.forms import ModelForm
from django import forms


class CategoryEditForm(ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0,
                                  max_value=90, initial=0)

    class Meta:
        model = Category
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/models/products.py
from mainapp.models import Product
from django.forms import ModelForm


class ProductEditForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/models/users.py
from authapp.models import CustomUser
from django.forms import ModelForm


class UserEditForm(ModelForm):
    class Meta:
        model = CustomUser

        exclude = (
            'id',
            'password',
            'groups',
            'user_permissions',
            'is_staff',
        )

    def __init__(self, *args, **kwargs):
        readonly_fields = (
            'last_login',
            'date_joined'
        )
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field in readonly_fields:
            self.fields[field].widget.attrs['readonly'] = True
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views/categories.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from django.contrib.auth.decorators import user_passes_test
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection

from mainapp.models import Category
from adminapp.models.categories import CategoryEditForm


@user_passes_test(lambda user: user.is_superuser)
def index(request: HttpRequest):
    models = Category.objects.all()

    context = {
        'title': 'Categories list',
        'models': models,
    }

    return render(request, 'adminapp/categories/index.html', context)


@user_passes_test(lambda user: user.is_superuser)
def create(request: HttpRequest):
    if request.method == 'POST':
        form = CategoryEditForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:categories'))
    else:
        form = CategoryEditForm()

    context = {
        'title': 'Category create',
        'form': form,
    }

    return render(request, 'adminapp/categories/update.html', context)


@user_passes_test(lambda user: user.is_superuser)
def read(request: HttpRequest, pk):
    model = get_object_or_404(Category, pk=pk)
    context = {
        'title': 'Category',
        'object': model,
        'products': model.products.all().order_by('is_active')[:5],
    }

    return render(request, 'adminapp/categories/read.html', context)


@user_passes_test(lambda user: user.is_superuser)
def update(request: HttpRequest, pk):
    model = get_object_or_404(Category, pk=pk)

    if request.method == 'POST':
        form = CategoryEditForm(request.POST, request.FILES, instance=model)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('adminapp:category_read', args=[model.pk]))
    else:
        form = CategoryEditForm(instance=model)

    context = {
        'title': 'Category update',
        'form': form,
        'object': model,
    }

    return render(request, 'adminapp/categories/update.html', context)


@user_passes_test(lambda user: user.is_superuser)
def delete(request: HttpRequest, pk):
    model = get_object_or_404(Category, pk=pk)

    if request.method == 'POST':
        model.is_active = False
        model.save()
        return HttpResponseRedirect(reverse('admin:categories'))

    context = {
        'title': 'Category delete',
        'object': model,
    }

    return render(request, 'adminapp/categories/delete.html', context)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=Category)
def product_is_active_update_category_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.products.all().update(is_active=True)
        else:
            instance.products.all().update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)

adminapp/views/products.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import user_passes_test
from mainapp.models import Category, Product
from adminapp.models.products import ProductEditForm


def get_product_categories(pk):
    product = Product.objects.get(pk=pk)
    return product.category.all()


@user_passes_test(lambda user: user.is_superuser)
def create(request: HttpRequest, pk):
    title = 'продукт/создание'
    category = get_object_or_404(Category, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        product_form = ProductEditForm(initial={'category': category})

    content = {
        'title': title,
        'form': product_form,
        'category': category
    }

    return render(request, 'adminapp/products/update.html', content)


@user_passes_test(lambda user: user.is_superuser)
def read(request: HttpRequest, pk):
    title = 'Product'
    product = get_object_or_404(Product, pk=pk)
    content = {
        'title': title,
        'object': product,
        'categories': get_product_categories(pk)
    }

    return render(request, 'adminapp/products/read.html', content)


@user_passes_test(lambda user: user.is_superuser)
def list_by_category(request: HttpRequest, pk, page=1):
    title = 'админка/продукт'

    category = get_object_or_404(Category, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by(
        '-is_active')

    provider = Paginator(products_list, 5)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    content = {
        'title': title,
        'category': category,
        'page_obj': products_provider,
    }

    return render(request, 'adminapp/products/index.html', content)


@user_passes_test(lambda user: user.is_superuser)
def update(request: HttpRequest, pk):
    title = 'продукт/редактирование'

    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES,
                                    instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(
                reverse('admin:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {
        'title': title,
        'form': edit_form,
        'object': edit_product
    }

    return render(request, 'adminapp/products/update.html', content)


@user_passes_test(lambda user: user.is_superuser)
def delete(request: HttpRequest, pk):
    title = 'продукт/удаление'

    product = get_object_or_404(Product, pk=pk)

    categories = get_product_categories(pk)

    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(
            reverse('admin:product_read', args=[product.pk]))

    content = {
        'title': title,
        'object': product,
        'categories': categories
    }

    return render(request, 'adminapp/products/delete.html', content)

adminapp/views/users.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import user_passes_test
from authapp.forms import RegisterForm
from authapp.models import CustomUser
from adminapp.models.users import UserEditForm


@user_passes_test(lambda user: user.is_superuser)
def index(request: HttpRequest, page=1):
    users = CustomUser.objects.all()

    provider = Paginator(users, 10)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    content = {
        'page_obj': products_provider,
    }

    return render(request, 'adminapp/users/index.html', content)


@user_passes_test(lambda user: user.is_superuser)
def create(request: HttpRequest):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        form = RegisterForm()

    content = {
        'title': 'Users create',
        'form': form
    }

    return render(request, 'adminapp/users/update.html', content)


@user_passes_test(lambda user: user.is_superuser)
def read(request: HttpRequest, pk):
    user_profile = get_object_or_404(CustomUser, pk=pk)
    content = {
        'title': 'User view',
        'object': user_profile,
    }

    return render(request, 'adminapp/users/read.html', content)


@user_passes_test(lambda user: user.is_superuser)
def update(request: HttpRequest, pk):
    user_profile = get_object_or_404(CustomUser, pk=pk)

    if request.method == 'POST':
        form = UserEditForm(request.POST, request.FILES,
                            instance=user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('adminapp:user_read', args=[user_profile.id]))
    else:
        form = UserEditForm(instance=user_profile)

    content = {
        'title': 'Users update',
        'form': form,
        'object': user_profile,
    }

    return render(request, 'adminapp/users/update.html', content)


@user_passes_test(lambda user: user.is_superuser)
def delete(request: HttpRequest, pk):
    user_profile = get_object_or_404(CustomUser, pk=pk)

    if request.method == 'POST':
        user_profile.is_active = False
        user_profile.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {
        'title': 'Users delete',
        'object': user_profile,
    }

    return render(request, 'adminapp/users/delete.html', content)

adminapp/templates/adminapp/users/delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="confirmation-page">
        Уверены, что хотите удалить пользователя
        <strong>{{ object.username }}</strong>?
        <form class="confirmation-page__form" action="{% url 'admin:user_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <div class="input-form__submit-buttons">
                <button type="submit" class="form-control">
                    Delete
                </button>
                <button type="button" class="form-control">
                    <a href="{% url 'admin:user_read' object.pk %}">Cancel</a>
                </button>
            </div>
        </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/users/index.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <hr>
    <div class="categories_list">
        <h1>Users list</h1>
        <div class="admin-control">
            <a href="{% url 'admin:user_create' %}"
               class="button input-form__button admin-control__button">add new
            </a>
            {% if page_obj.has_previous %}
                <a href="
                        {% url 'admin:users' %}{{ page_obj.previous_page_number }}"
                   class="button product-pagination__button"><i
                        class="fas fa-angle-left"></i></a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="
                        {% url 'admin:users' %}{{ page_obj.next_page_number }}"
                   class="button product-pagination__button"><i
                        class="fas fa-angle-right"></i></a>

            {% endif %}
        </div>
        {% for user_profile in page_obj %}
            <div class="category_record {% if not user_profile.is_active %}not_active{% endif %}">
                <div class="background admin-product-image"
                     style="background-image: url({{ user_profile.avatar|media_folder_files }})">
                </div>
                <div class="category_name">
                    <p>{{ user_profile.username|title }}</p>
                    <p>({{ user_profile.first_name|title }}
                        {{ user_profile.last_name|title }})</p>
                </div>
                <div class="category_actions">
                    <a href="{% url 'admin:user_read' pk=user_profile.id %}"
                       class="button input-form__button admin-control__button">view</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/users/read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <hr>
    <div class="categories_list">
        <div class="category_name">
            <h1 class="{% if not object.is_active %}not_active{% endif %}">
                login: {{ object.username }}
            </h1>
        </div>
        <ul>
            {% if object.first_name %}
                <li class="menu__list">Имя: {{ object.first_name }}</li>
            {% endif %}
            {% if object.last_name %}
                <li class="menu__list">Фамилия: {{ object.last_name }}</li>
            {% endif %}
            <li class="menu__list">E-mail: {{ object.email }}</li>
            <li class="menu__list">Возраст: {{ object.age }}</li>
        </ul>
        {% if object.avatar %}
            <div class="background products__item user_avatar"
                 style="background-image: url({{ object.avatar|media_folder_files }}">
            </div>
        {% endif %}
        <div class="admin-control">
            <a href="{% url 'admin:user_update' pk=object.id %}"
               class="button input-form__button admin-control__button">Update</a>
            {% if object.is_active %}
                <a href="{% url 'admin:user_delete' pk=object.id %}"
                   class="button input-form__button admin-control__button">Delete</a>
            {% endif %}
            <a href="{% url 'admin:users' %}"
               class="button input-form__button admin-control__button">Back</a>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/users/update.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <hr>
    <div class="confirmation-page">
        {% if object.avatar %}
            <div class="background products__item user_avatar"
                 style="background-image: url({{ object.avatar|media_folder_files }}">
            </div>
        {% endif %}
        <h1 class="{% if not object.is_active %}not_active{% endif %}">
            {{ object.username|title }}
        </h1>
        <form class="confirmation-page__form" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="input-form__submit-buttons">
                <button type="submit" class="form-control">
                    Save
                </button>
                <button type="button" class="form-control">
                    <a href="
                        {% if object %}
                        {% url 'admin:user_read' object.pk %}
                        {% else %}
                        {% url 'admin:users' %}
                        {% endif %}">Cancel
                    </a>
                </button>
            </div>
        </form>
    </div>
{% endblock %}