authapp/urls.py
from django.urls import path

import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    path('', controller.redirect_to_login, name='index'),
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),
    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/',
         controller.verify, name='verify'),
]

geekmarket/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
import mainapp.views as controller

urlpatterns = [
    path('contacts/', controller.contacts, name='contacts'),

    path('products/', include('mainapp.catalog_urls', namespace='catalog')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='home')),

    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

ordersapp/urls.py
from controllers import ListViews, CreateViews, UpdateViews, DeleteViews, \
    DetailViews
import ordersapp.views as ordersapp
from django.urls import path

app_name = "ordersapp"

urlpatterns = [
    path('', ListViews.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/',
         ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', CreateViews.OrderItemsCreate.as_view(),
         name='order_create'),
    path('read/<int:pk>/', DetailViews.OrderRead.as_view(),
         name='order_read'),
    path('update/<int:pk>/', UpdateViews.OrderItemsUpdate.as_view(),
         name='order_update'),
    path('delete/<int:pk>/', DeleteViews.OrderDelete.as_view(),
         name='order_delete'),
    path('product/<int:pk>/price/', ordersapp.get_product_price),
]

ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(db_index=True, verbose_name='активен',
                                    default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.id}'

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(
                list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self, *args, **kwargs):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


# class OrderItemQuerySet(models.QuerySet):
#
#     def delete(self, *args, **kwargs):
#         for item in self:
#             item.product.quantity += item.quantity
#             item.product.save()
#         super(OrderItemQuerySet, self).delete(*args, **kwargs)


class OrderItem(models.Model):
    # objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order,
                              related_name="orderitems",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    @property
    def get_product_cost(self):
        return self.product.price * self.quantity

    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.__class__.get_items(
    #             self.pk).quantity
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super(self.__class__, self).save(*args, **kwargs)

    # def delete(self, *args, **kwargs):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(self.__class__, self).delete()

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem
from mainapp.models import Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.get_items().select_related()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['min'] = 0

ordersapp/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.http import HttpRequest, JsonResponse
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete

from django.db.models import F
from ordersapp.models import Order, OrderItem
from basketapp.models import Basket
from mainapp.models import Product


def order_forming_complete(request: HttpRequest, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:orders_list'))


def get_product_price(request, pk):
    if request.is_ajax():
        product = get_object_or_404(Product, pk=int(pk))
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk and sender.get_item(instance.pk) is not None:
            instance.product.quantity = F('quantity') - (
                    instance.quantity - sender.get_item(
                instance.pk).quantity)
            # instance.product.quantity -= instance.quantity - sender.get_item(
            #     instance.pk).quantity
        else:
            instance.product.quantity = F('quantity') - instance.quantity
        #     instance.product.quantity -= instance.quantity
        # instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity = F('quantity') + instance.quantity
    # instance.product.save()

ordersapp/templates/ordersapp/include/inc_order_actions.html
{% if object.status == 'FM' %}
    <a href="{% url 'order:order_forming_complete' object.pk %}"
       class="button input-form__button">
        совершить покупку
    </a>
    <a href="{% url 'order:order_delete' object.pk %}"
       class="button input-form__button">удалить</a>
{% endif %}
<a href="{% url 'order:orders_list' %}" class="button input-form__button">
    к списку заказов
</a>

ordersapp/templates/ordersapp/include/inc_order_summary.html
{% load custom_tags %}

{% if object %}

    <div class="h2">Заказ №{{ object.pk }}
        от {{ object.created|date:"Y-m-d H:i:s" }}</div>
    <hr>
    <div class="order-detail">
        <div class="summary summary__right">
            <b>Заказчик:</b>
            <b>Обновлен:</b>
            <b>Статус:</b>
            <b>Общее количество товаров:</b>
            <b>Общая стоимость:</b>
        </div>
        <div class="summary">
            {% with object_summary=object.get_summary %}
                <p>{{ object.user.last_name|default:"User" }} {{ object.user.first_name }}</p>
                <p>{{ object.updated|date:"Y-m-d H:i:s" }}</p>
                <p>{{ object.get_status_display }}</p>
                <p class="order_total_quantity">{{ object_summary.total_quantity }}</p>
                <p class="order_total_cost">{{ object_summary.total_cost|currency }}</p>
            {% endwith %}
        </div>
    </div>
{% else %}
    <div class="h2">Новый заказ</div>
    <hr>

    <div class="order-detail">
        <div class="summary summary__right">
            <b>Заказчик:</b>
            {% if basket.0 %}
                <b>Общее количество товаров:</b>
                <b>Общая стоимость:</b>
            {% endif %}
        </div>
        <div class="summary">
            <p>{{ user.last_name|default:"User" }} {{ user.first_name }}</p>
            {#            {% if basket.0 %}#}
            <p class="order_total_quantity"></p>
            {#                <p class="order_total_quantity">{{ basket.0.total_quantity }}</p>#}
            <p><span class="order_total_cost"></span></p>
            {#                <p><span class="order_total_cost">{{ basket.0.total_cost|currency }}</span></p>#}
            {#            {% endif %}#}
        </div>
    </div>
{% endif %}
<hr>   