adminapp/urls.py
from django.urls import path

from adminapp.views import users, categories, products
from controllers import ListViews, CreateViews, UpdateViews, DeleteViews, \
    DetailViews

app_name = 'adminapp'

urlpatterns = [
    # users

    # FBV
    # path('users/index/', users.index, name='users'),
    # path('users/index/<int:page>', users.index, name='users_page'),
    # path('users/create/', users.create, name='user_create'),
    # path('users/read/<int:pk>', users.read, name='user_read'),
    # path('users/update/<int:id>', users.update, name='user_update'),
    # path('users/delete/<int:pk>/', users.delete, name='user_delete'),

    # CBV
    path('users/index/', ListViews.UserListView.as_view(), name='users'),
    path('users/index/<int:page>/', ListViews.UserListView.as_view(),
         name='users_page'),
    path('users/create/', CreateViews.UserCreateView.as_view(),
         name='user_create'),
    path('users/read/<int:pk>/', DetailViews.UserDetailView.as_view(),
         name='user_read'),
    path('users/update/<int:pk>/', UpdateViews.UserUpdateView.as_view(),
         name='user_update'),
    path('users/delete/<int:pk>/', DeleteViews.UserDeleteView.as_view(),
         name='user_delete'),

    # categories

    # FBV
    # path('categories/index/', categories.index, name='categories'),
    # path('categories/create/', categories.create, name='category_create'),
    # path('categories/read/<int:pk>/', categories.read, name='category_read'),
    # path('categories/update/<int:pk>/', categories.update,
    #      name='category_update'),
    # path('categories/delete/<int:pk>/', categories.delete,
    #      name='category_delete'),

    # CBV
    path('categories/index/', ListViews.CategoryListView.as_view(),
         name='categories'),
    path('categories/index/<int:page>/', ListViews.CategoryListView.as_view(),
         name='categories_page'),
    path('categories/create/', CreateViews.CategoryCreateView.as_view(),
         name='category_create'),
    path('categories/read/<int:pk>/', DetailViews.CategoryDetailView.as_view(),
         name='category_read'),
    path('categories/update/<int:pk>/',
         UpdateViews.CategoryUpdateView.as_view(),
         name='category_update'),
    path('categories/delete/<int:pk>/',
         DeleteViews.CategoryDeleteView.as_view(),
         name='category_delete'),

    # products

    # FBV
    # path('products/list/<int:pk>/', products.list_by_category,
    #      name='products'),
    # path('products/list/<int:pk>/<int:page>/', products.list_by_category,
    #      name='products_page'),
    # path('products/create/<int:pk>/', products.create, name='product_create'),
    # path('products/read/<int:pk>/', products.read, name='product_read'),
    # path('products/update/<int:pk>/', products.update, name='product_update'),
    # path('products/delete/<int:pk>/', products.delete, name='product_delete'),

    # CBV
    path('products/list/<int:pk>/', ListViews.ProductListView.as_view(),
         name='products'),
    path('products/list/<int:pk>/<int:page>/',
         ListViews.ProductListView.as_view(),
         name='products_page'),
    path('products/create/<int:pk>/', CreateViews.ProductCreateView.as_view(),
         name='product_create'),
    path('products/read/<int:pk>/', DetailViews.ProductDetailView.as_view(),
         name='product_read'),
    path('products/update/<int:pk>/', UpdateViews.ProductUpdateView.as_view(),
         name='product_update'),
    path('products/delete/<int:pk>/', DeleteViews.ProductDeleteView.as_view(),
         name='product_delete'),

    # orders
    path('order/restore/<int:pk>/', UpdateViews.OrderItemsUpdate.as_view(),
         name='order_restore'),
    path('orders/list/', ListViews.OrderList.as_view(),
         name='orders'),
    path('orders/list/<int:page>/', ListViews.OrderList.as_view(),
         name='orders_page'),

]

authapp/urls.py
from django.urls import path

import authapp.views as controller

app_name = 'authapp'

urlpatterns = [
    path('', controller.redirect_to_login, name='index'),
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),
    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/',
         controller.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('change/<int:pk>/', basketapp.basket_change, name='change'),
    path('delete/<int:pk>/', basketapp.basket_delete, name='delete'),
    # path('add/<int:pk>/', basketapp.basket_add, name='add'),
    # path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

geekmarket/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
import mainapp.views as controller

urlpatterns = [
    path('contacts/', controller.contacts, name='contacts'),

    path('products/', include('mainapp.catalog_urls', namespace='catalog')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
    path('', include('mainapp.urls', namespace='home')),

    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

mainapp/urls.py
from django.urls import path

import mainapp.views as controller

app_name = 'mainapp'

urlpatterns = [
    path('', controller.index, name='index'),
    path('<str:current_product_category>/', controller.index, name='category'),
]

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpRequest
from .models import Product, Category, CatalogMenu, NewMenu, Address
from random import sample
import os
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.template.loader import render_to_string
from django.http import JsonResponse


def products_ajax(request: HttpRequest, current_product_category='', page=1):
    if current_product_category != '':
        get_object_or_404(CatalogMenu,
                          category__name=current_product_category,
                          category__is_active=True)
        catalog_menu_products = get_products_by_category_price_cached(
            current_product_category)
    else:
        catalog_menu_products = get_products_by_category_price_cached('')

    provider = Paginator(catalog_menu_products, 6)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    catalog_menu_links = get_catalog_menu_links_cached()

    used_product_categories = ['exclusive', 'promo']

    context = {
        'title': 'Catalog',
        'catalog_menu_links': catalog_menu_links,
        'current_product_category': current_product_category,
        'provider': products_provider,
    }

    for category in used_product_categories:
        if Category.objects.filter(name=category, is_active=True).first():
            _temp = list(Product.objects.filter(category__name=category,
                                                is_active=True))
            if _temp:
                context[category + '_products'] = sample(_temp,
                                                         len(_temp))

    result = render_to_string(
        'mainapp/include/inc_products_list_content.html',
        context=context,
        request=request)

    return JsonResponse({'result': result})


def index(request: HttpRequest, current_product_category=''):
    if current_product_category != '':
        get_object_or_404(NewMenu,
                          category__name=current_product_category,
                          pk__gt=1,
                          category__is_active=True)
        new_menu_products = get_products_by_category_random(
            current_product_category)
    else:
        if get_new_menu_check_cached():
            new_menu_products = get_products_by_category_random(
                get_new_menu_check()[0]['category__name'])
        else:
            new_menu_products = []

    new_menu_links = get_new_menu_links_cached()

    used_product_categories = ['trending', 'exclusive', 'promo', 'hot']

    context = {
        'title': 'Main',
        'new_menu_links': new_menu_links,
        'current_product_category': current_product_category,
        'new_menu_products': new_menu_products,
    }

    for category in used_product_categories:
        if Category.objects.filter(name=category, is_active=True).values(
                'id').first():
            if get_products_by_category_random(category):
                context[
                    category + '_products'] = get_products_by_category_random(
                    category)

    return render(request, 'mainapp/index.html', context)


def products(request: HttpRequest, current_product_category='', page=1):
    if current_product_category != '':
        get_object_or_404(CatalogMenu,
                          category__name=current_product_category,
                          category__is_active=True)
        catalog_menu_products = get_products_by_category_price_cached(
            current_product_category)
    else:
        catalog_menu_products = get_products_by_category_price_cached('')

    provider = Paginator(catalog_menu_products, 6)

    try:
        products_provider = provider.page(page)
    except PageNotAnInteger:
        products_provider = provider.page(1)
    except EmptyPage:
        products_provider = provider.page(provider.num_pages)

    catalog_menu_links = get_catalog_menu_links_cached()

    used_product_categories = ['exclusive', 'promo']

    context = {
        'title': 'Catalog',
        'catalog_menu_links': catalog_menu_links,
        'current_product_category': current_product_category,
        'provider': products_provider,
    }

    for category in used_product_categories:
        if Category.objects.filter(name=category, is_active=True).first():
            _temp = list(Product.objects.filter(category__name=category,
                                                is_active=True))
            if _temp:
                context[category + '_products'] = sample(_temp,
                                                         len(_temp))

    return render(request, 'mainapp/products.html', context)


def details(request: HttpRequest, product_id=None, color=None, size=None):
    current_product = get_product(product_id)

    if current_product.big_img_path and size is None:
        image_link = current_product.big_img_path.url
        if color:
            split = os.path.split(image_link)
            check_color = split[0] + str(color) + split[1]
            image_link = check_color if os.path.exists(
                check_color) else current_product.big_img_path.url
    elif current_product.small_img_path:
        image_link = current_product.small_img_path.url
    else:
        image_link = ''

    catalog_menu_links = get_catalog_menu_links()

    same_products = list(
        Product.objects.exclude(pk=product_id).filter(is_active=True,
                                                      category__in=current_product.category.filter(
                                                          is_active=True)))
    context = {
        'title': current_product.title,
        'catalog_menu_links': catalog_menu_links,
        'color': color,
        'current_product': current_product,
        'product_id': product_id,
        'img_link': image_link,
        'same_products': sample(same_products, len(same_products)),
        'product_desc': current_product.full_description,
        'product_price': current_product.price,
    }

    return render(request, 'mainapp/details.html', context)


def contacts(request: HttpRequest):
    addresses = list(Address.objects.all())
    context = {
        'addresses': addresses,
        'title': 'Contacts',
    }
    return render(request, 'mainapp/contacts.html', context)


def get_catalog_menu_links():
    catalog_menu_links = [{'title': 'all',
                           'category__name': ''}] + list(
        CatalogMenu.objects.select_related('category').filter(
            category__is_active=True).values(
            'title',
            'category__name'))

    return catalog_menu_links


def get_catalog_menu_links_cached():
    if settings.LOW_CACHE:
        key = 'catalog_menu_links_cached'
        catalog_menu_links_cached = cache.get(key)
        if catalog_menu_links_cached is None:
            catalog_menu_links_cached = get_catalog_menu_links()
            cache.set(key, catalog_menu_links_cached)
        return catalog_menu_links_cached
    else:
        return get_catalog_menu_links()


def get_new_menu_check():
    return NewMenu.objects.select_related('category').filter(
        category__is_active=True).values('title', 'category_id',
                                         'category__name')


def get_new_menu_check_cached():
    if settings.LOW_CACHE:
        key = 'new_menu_check_cached'
        new_menu_check_cached = cache.get(key)
        if new_menu_check_cached is None:
            new_menu_check_cached = get_new_menu_check()
        return new_menu_check_cached
    else:
        return get_new_menu_check()


def get_new_menu_links():
    if get_new_menu_check_cached():
        new_menu_links = [{'title': get_new_menu_check_cached()[0]['title'],
                           'category__name': ''}] + list(
            get_new_menu_check_cached().values('title', 'category__name')[1:])
    else:
        new_menu_links = []

    return new_menu_links


def get_new_menu_links_cached():
    if settings.LOW_CACHE:
        key = 'new_menu_links_cached'
        new_menu_links_cached = cache.get(key)
        if new_menu_links_cached is None:
            new_menu_links_cached = get_new_menu_links()
            cache.set(key, new_menu_links_cached)
        return new_menu_links_cached
    else:
        return get_new_menu_links()


def get_products_by_category_price(category):
    if category == '':
        products_price = Product.objects.filter(is_active=True).order_by(
            'price')
    else:
        products_price = Product.objects.prefetch_related('category').filter(
            category__name=category, is_active=True).order_by('price')
    return products_price


def get_products_by_category_price_cached(category):
    if settings.LOW_CACHE:
        key = f'products_by_category_price_cached{category}'
        products_by_category_price_cached = cache.get(key)
        if products_by_category_price_cached is None:
            products_by_category_price_cached = get_products_by_category_price(
                category)
            cache.set(key, products_by_category_price_cached)
        return products_by_category_price_cached
    else:
        return get_products_by_category_price(category)


def get_products_by_category_random(category):
    _temp = list(get_products_by_category_price_cached(category))
    return sample(_temp, len(_temp))


def get_product(product_id):
    if settings.LOW_CACHE:
        key = f'product_{product_id}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=product_id, is_active=True)
            cache.set(key, product)
        return product
    else:

mainapp/templates/mainapp/widgets/catalog_menu.html
{% load static %}
<ul class="menu {% if request.resolver_match.url_name == 'product' %} background detail-menu {% endif %}">
    {% for link in catalog_menu_links %}
        <li class="menu__list">
            <a href="{% url 'catalog:index' %}{% if link.category__name %}{{ link.category__name|lower }}/{% endif %}"
               class="menu__link products-menu__link {% if request.resolver_match.url_name == 'product' %} detail-menu__link {% endif %} {% if current_product_category == link.category__name|lower %} menu__link_active {% endif %}">{{ link.title }}
            </a>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/widgets/header.html
{% load static %}
{% load custom_tags %}
<header class="header">
    <a class="logo" href="{% url 'home:index' %}"><img
            src="{% static 'img/logo.svg' %}" alt="logo"></a>
    <nav>
        <ul class="menu">
            {% for item in main_menu_links %}
                <li class="menu__list"><a
                        href="{% url item.link %}{{ item.category }}"
                        class="menu__link
    {% if request.resolver_match.namespace|add:':index' == item.link or request.resolver_match.view_name == item.link %}
        menu__link_active
    {% endif %}">{{ item.title }}
                </a>
                </li>
            {% endfor %}
            {% if user.is_authenticated %}
                <li class="menu__list">
                    <div class="dropdown">
                        <a class="dropdown-toggle menu__link {% if request.resolver_match.view_name == 'order:orders_list' or request.resolver_match.view_name == 'auth:edit' %} menu__link_active {% endif %}" href=""
                           data-toggle="dropdown">
                            {{ user.first_name|default:'User' }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'auth:edit' %}"
                                   class="menu__link">
                                    Profile
                                    ({{ user.first_name|default:'user' }})
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'order:orders_list' %}"
                                   class="menu__link">
                                    Orders
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                {% if user.is_superuser %}
                    <li class="menu__list">
                        <a href="{% url 'admin:categories' %}"
                           class="menu__link {% if request.resolver_match.namespace == 'admin' %} menu__link_active {% endif %}">
                            Admin panel
                        </a>
                    </li>
                {% endif %}
                <li class="menu__list"><a href="{% url 'auth:logout' %}"
                                          class="menu__link">logout</a></li>
            {% else %}
                <li class="menu__list">
                    <a href="{% url 'auth:register' %}"
                       class="menu__link {% if request.resolver_match.view_name == 'auth:register' %} menu__link_active {% endif %}">sign
                        up
                    </a>
                </li>
                <li class="menu__list"><a href="{% url 'auth:login' %}"
                                          class="menu__link {% if request.resolver_match.view_name == 'auth:login' %} menu__link_active {% endif %}">sign
                    in</a></li>
            {% endif %}
            <li class="menu__list search"><img
                    src="{% static 'img/search.svg' %}" alt="search"></li>
            <li class="menu__list search">
                <a href="{% url 'basket:view' %}" alt="basket" class="basket">
                    <span class="basket-info">
                        {% if basket %}
                            <p><span class="basket-item-total-quantity">{{ basket.0.total_quantity }}</span> товаров</p>
                            <p>$<span class="basket-item-total-cost">{{ basket.0.total_cost|normalize}}</span></p>
                        {% endif %}
                    </span>
                </a>
            </li>
        </ul>
    </nav>
</header>

mainapp/templates/mainapp/widgets/new_menu.html
{% load static %}
<ul class="new-menu">
    {% for link in new_menu_links %}
        <li class="new-menu__list">
            <a href="{% url 'home:index' %}{{ link.category__name|lower }}"
               class="new-menu__link {% if current_product_category == link.category__name|lower %} new-menu__link_active {% endif %}"
            >{{ link.title }}
            </a>
        </li>
    {% endfor %}
</ul>